function setPARROTCodeGen()
% SETPARROTCODEGEN This function sets the appropriate settings
% for code generation for the controller. This is a private function, not
% meant to be used directly.

% Copyright 2017 The MathWorks, Inc.

% Check that the support package is installed
if isParrotSupportPkgInstalled
    % Check if the flight control system model and its children are open
    model = {'flightControlSystem','flightController','stateEstimator'};
    for k = 1:length(model)
        isFCSLoaded = bdIsLoaded(model{k});
        if ~isFCSLoaded
            load_system(model{k});
        end

        % Set the hardware target toolchain
        set_param(model{k},...
            'HardwareBoard','PARROT Rolling Spider',...
            'DefaultParameterBehavior','Tunable',...
            'MaxStackSize','64',...
            'UseEmbeddedCoderFeatures', 'on',...
            'Toolchain','Sourcery G++ Lite GNU Toolchain for Drones',...
            'GenCodeOnly', 'off',...
            'TLCOptions', '-aInlineSetEventsForThisBaseRateFcn=TLC_FALSE -aSuppressMultiTaskScheduler=TLC_FALSE -aRateBasedStepFcn=1',...
            'PostCodeGenCommand', 'codertarget.postCodeGenHookCommand(h)',...
            'GenerateSampleERTMain', 'off',...
            'ERTCustomFileTemplate', 'codertarget_file_process.tlc',...
            'CoderTargetData', struct('UseCoderTarget',true,'TargetHardware',...
            'PARROT Rolling Spider','RTOS','Baremetal','Runtime',...
            struct('BuildAction','Build'),'Clocking',struct('cpuClockRateMHz','416'),...
            'DataVersion','2016.02'));

        % Only save is model is not opened, just in case there are unsaved changes
        if ~isFCSLoaded
            save_system(model{k});
        end
    end
else
    warning(message('aeroblks:asbquadcopter:supportPkgNotInstalled'));
end